### ISSUE TITLE
Fehlermeldung mit PHP 7.3

### ISSUE THREAD

**Issue by a-kehr** [netzmacht/contao-form-designer#2]
Bei Benutzung von PHP 7.3 erscheint folgende Fehlermeldung.

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

Folgende Datei **src/Listener/ThemeImportListener.php** in **Zeile 109** ist betroffen.

**Comment by dmolineus** [comment]
Fixed with 3e6f6a91a6d834320bf0fdb6916ca02fd7d8308d.
