### ISSUE TITLE
Sicherheitsfrage kann nicht gelöst werden

### ISSUE THREAD

**Issue by marcoheinz** [netzmacht/contao-form-designer#38]
Nach Update auf von Contao 4.13.36 auf 4.13.37 kann die Sicherheitsfrage durch korrekte Eingabe nicht gelöst werden.
Workaround:
In templates ein form_captcha.html aus contao/core-bundle anlegen.

**Comment by dmolineus** [comment]
Thanks for reporting. Fixed in this 1.4.4. The issue still might occur if any other package based on this bundle provides custom form control templates.
