### ISSUE TITLE
Sicherheitsabfrage

### ISSUE THREAD

**Issue by speedweb** [netzmacht/contao-form-designer#39]
Hallo,
- Formular wird ohne Sicherheitsabfrage angezeigt.
- beim absenden des Formular wird dieses erneut angezeigt (mit Sicherheitsabfrage)
- Sicherheitsabfrage kann richtig beantwortet werden, aber das Formular lässt sich nicht absenden.

nach entfernen der Erweiterung Funktionieren alle Formulare wieder wie bisher.

CONTAO: 4.13.38
PHP: 8.0.3

beste Grüße
Thomas Schwendinger

**Comment by dmolineus** [comment]
Problem wurde bereits am 13. Februar mit der Version 1.4.4 behoben. Jedoch setzt diese PHP 8.1 voraus. PHP 8.0 ist End of Life, siehe https://www.php.net/supported-versions.php. Die Readme habe ich entsprechend angepasst.

**Comment by speedweb** [comment]
Besten Dank für die Info.
Leider kann ich noch nicht auf PHP 8.1 wechseln, da noch weitere Applikationen

Dafür angepasst werden müssen.

 

Beste Grüße
Thomas

 

Von: David Molineus ***@***.***> 
Gesendet: Montag, 11. März 2024 08:32
An: netzmacht/contao-form-designer ***@***.***>
Cc: speedweb ***@***.***>; Author ***@***.***>
Betreff: Re: [netzmacht/contao-form-designer] Sicherheitsabfrage (Issue #39)

 

Problem wurde bereits am 13. Februar mit der Version 1.4.4 behoben. Jedoch setzt diese PHP 8.1 voraus. PHP 8.0 ist End of Life, siehe https://www.php.net/supported-versions.php. Die Readme habe ich entsprechend angepasst.
